### ISSUE TITLE
Detect git repo

### ISSUE THREAD

**Issue by khattakdev** [khattakdev/minimalcommit#1]
On using the command `mct`, the package should detect if it's a git repo or not. If not, it should return an error message saying **The directory is not a git repository**.

**Comment by shahmeerzaidi** [comment]
@khattakdev , could you please assign this issue to me? I have already fixed the issue and would like to push the changes. Thank you!

**Comment by khattakdev** [comment]
@shahmeerzaidi assigned

**Comment by shahmeerzaidi** [comment]
you assigned it to yourself :D
