### ISSUE TITLE
MCT allowing commit even git is not configured

### ISSUE THREAD

**Issue by Junaid300** [khattakdev/minimalcommit#15]
I have a vitejs project without `git` configuration. I tried to run `mct` and it worked for it. It should check is this project configured with the git or bit then should allow adding commit.

I have attached screenshot.
![image](https://user-images.githubusercontent.com/66414908/230568134-d0c2c700-08eb-4a67-bf0e-44c469da3a12.png)

**Comment by UmairJibran** [comment]
Hey, @Junaid300 thanks for reporting this, this issue was fixed by @shahmeerzaidi in #1 but has not yet been published on npm.

@khattakdev please publish the new release, we should think about automating the release as well

**Comment by Junaid300** [comment]
@UmairJibran , got it thank you.
