### ISSUE TITLE
Choice for test case

### ISSUE THREAD

**Issue by UmairJibran** [khattakdev/minimalcommit#16]
we should have an additional choice for when adding test case

**Comment by khattakdev** [comment]
Can you explain more please

**Comment by UmairJibran** [comment]
![image](https://user-images.githubusercontent.com/43789374/230791914-32a1a2fd-25ed-46fc-a774-0cc0859963bf.png)
Test Cases do not fall under these types, I think we should have another type so if we have added test case we can include it

**Comment by khattakdev** [comment]
Can you work on this?

This includes adding `test` to the `README.md` as well.
Use 🧪 as an emoji

**Comment by UmairJibran** [comment]
I'll add it to my the current active PR #13

**Comment by UmairJibran** [comment]
achieved in #13
