### ISSUE TITLE
--help argument

### ISSUE THREAD

**Issue by khattakdev** [khattakdev/minimalcommit#17]
When execute `mct --help`, the user should get the following result:

`✨ feat` to be used for a new feature
`🐛 fix` to be used for bug fixes
`💥 break` to be used for breaking changes
`♻️ ref` to be used for making code/folder refactor
`🔖 ver` to be used for version changes
`📝 docs` to be used for documentation
`🎨 style` to be used for CSS changes
`🛠 config` for configuration and dependencies changes
`📦 misc` to be used for others

The type (e.g. `🎨 style`)  should have a white background (`chalk.bgWhite`).

**Comment by captainWaheed** [comment]
@khattakdev I want to work on this issue 🙌🏻

**Comment by Junaid300** [comment]
A suggestion,  It would be great if we show all commands for `mct --help`  with commit types list.

Here is the example.
| command| Description | type|
| ------------- |:-------------:| -----:|
| --help , -h     | Show help | boolean|
| --version, -v      | Show version number |   boolean |


![image](https://user-images.githubusercontent.com/66414908/230857940-4b94d82f-473a-4279-b1ce-aacbe20a086e.png)

**Comment by khattakdev** [comment]
@Junaid300 Great suggestion

@captainWaheed Go for the task but make it `mct --types` or `mct -t`

Later on, we will introduce `mct --help` but that should be a separate pull request.

**Comment by captainWaheed** [comment]
Sure! Noted...

**Comment by Junaid300** [comment]
Can i work on `--help` part ? I may need assistance for this. I am totally new to `CLI tools`.

**Comment by khattakdev** [comment]
@Junaid300 go for it.

**Comment by Junaid300** [comment]
@khattakdev , what library will we use to read `--help` part ?

**Comment by khattakdev** [comment]
> @khattakdev , what library will we use to read `--help` part ?

You can use [yargs](https://www.npmjs.com/package/yargs)

**Comment by Junaid300** [comment]
I need to ask few things related to this task. I am kind of confuse how will we check is there any flag with `mct` or not. For example `mct --help` is a valid command but `mct --version` , we don't have this command yet. If i use switch or if-else  then it may trigger `mct` that is kind of invalid. Like in `npm`  it will return `a small manual`. And If use invalid command it will return same `small manual`. How should i deal with this ? 
I hope you got my point.

**Comment by khattakdev** [comment]
> I am kind of confuse how will we check is there any flag with mct or not

With [Yargs](https://www.npmjs.com/package/yargs), you can add responses of specific commands. Go through the documentation and you will get an idea of how it works.

**Comment by Junaid300** [comment]
@khattakdev , 
I spent some time on yargs, it has low community, learning resources and i cam across `commander.js` . It  provide great features with good resources and community support.  What you say about this?
