### ISSUE TITLE
Adding backtick to commit throw error

### ISSUE THREAD

**Issue by cryogon** [khattakdev/minimalcommit#24]
git commit support backticks to highlight some parts of the text as code but using it with `mct` throw an error and also commits regardless; excluding text inside backticks.

**Comment by mafzaldev** [comment]
I have tried to reproduce the error. It does not show any error and displays the message with backticks as it should.
PS: Arsalan I just saw this issue's date, looks like you have fixed the issue till now.

![image](https://github.com/khattakdev/minimalcommit/assets/78255759/f00f91f1-6401-4ded-9c9a-d423f96c45c3)

**Comment by cryogon** [comment]
it works now, I'm closing the issue
