### ISSUE TITLE
Update ReadME

### ISSUE THREAD

**Issue by khattakdev** [khattakdev/minimalcommit#6]
1. Add the following graphics before `What is Minimal Commit?`.
![minimal commit](https://user-images.githubusercontent.com/37709578/229779509-22166f89-45f2-484d-a034-261da1b3c9c2.png)

**Note:** This Graphics should be hosted on GitHub (Similar to the following example)
`![Minimal Commit demo](https://user-images.githubusercontent.com/37709578/229569956-592effaa-63e6-4f15-8870-6c5f9061f19f.gif)`.

2. Add the Contribution section and make sure to add the following things:
- Before working on something, make sure there is an issue with it.
- Create an issue, if it doesn't exist
- If the issue is not taken, make a request and start working on it.
- If the issue has been assigned to someone and there have been no updates for more than two weeks, you can request to work on it.

If there is anything else that you want to add, please let me know first.

**Comment by udaymishra04** [comment]
i would like to work on this

**Comment by Haimantika** [comment]
Hi 👋 would love to help with this one :)

**Comment by Haimantika** [comment]
Made a PR, if everything is fine, we will need to change the Contributing Guide hyperlink in the Readme. Also @khattakdev you may want to add a CoC in future, especially if you have a community around this.
